hyperskill_project:
  id: 190
  ide_files: https://cogniterra.org/media/attachments/lesson/25579/additional_files.json
  is_template_based: false
  use_ide: true
  environment: android
update_date: "Thu, 01 Jan 1970 00:00:00 UTC"
stages:
- id: 949
  step: 13537
  is_completed: false
- id: 950
  step: 13538
  is_completed: false
- id: 951
  step: 13539
  is_completed: false
- id: 952
  step: 13540
  is_completed: false
topics:
  0:
  - title: "Write, compile, and run"
    theory_id: 3739
  - title: "JVM, JRE, and JDK"
    theory_id: 3499
  - title: Interface elements
    theory_id: 15253
  - title: Input fields and field labels
    theory_id: 15447
  - title: Fonts
    theory_id: 15045
  - title: Units of information
    theory_id: 6865
  - title: IDE
    theory_id: 10996
  - title: Introduction to Operating systems
    theory_id: 9704
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and Options
    theory_id: 9746
  - title: Computer programming
    theory_id: 8739
  - title: Paradigms
    theory_id: 15860
  - title: Introduction to Kotlin
    theory_id: 4350
  - title: Basic literals
    theory_id: 4351
  - title: Overview of the basic program
    theory_id: 4362
  - title: Values and variables
    theory_id: 4371
  - title: Val variables
    theory_id: 17408
  - title: Data types
    theory_id: 4388
  - title: Comments
    theory_id: 4406
  - title: Coding style conventions
    theory_id: 4419
  - title: Naming variables
    theory_id: 4389
  - title: The classification of basic types
    theory_id: 4455
  - title: Type conversion
    theory_id: 4672
  - title: Standard output
    theory_id: 4425
  - title: Invoking functions
    theory_id: 4575
  - title: Standard input with Java Scanner
    theory_id: 4445
  - title: Reading data with a readln
    theory_id: 11224
  - title: String basics
    theory_id: 12553
  - title: String templates
    theory_id: 4547
  - title: Boolean and logical operations
    theory_id: 4515
  - title: Arithmetic operations
    theory_id: 4472
  - title: Type of the numeric expression
    theory_id: 9506
  - title: Increment and decrement
    theory_id: 10776
  - title: Integers in action
    theory_id: 4488
  - title: Relational operators
    theory_id: 4525
  - title: Declaring functions
    theory_id: 4580
  - title: Introduction to OOP
    theory_id: 3614
  - title: Build tools
    theory_id: 4284
  - title: Gradle basics
    theory_id: 5075
  - title: Objects
    theory_id: 11233
  - title: Declaring classes
    theory_id: 6200
  - title: Android studio basics
    theory_id: 11048
  - title: API Levels
    theory_id: 11312
  - title: External resources
    theory_id: 6216
  - title: Introduction to Android
    theory_id: 6331
  - title: XML
    theory_id: 6901
  - title: Android Project Structure
    theory_id: 10752
  - title: AndroidManifest File
    theory_id: 10762
  - title: Resources
    theory_id: 11087
  - title: Values
    theory_id: 11370
  - title: XML Layouts
    theory_id: 10997
  - title: build.gradle files
    theory_id: 15053
  - title: Android Studio Tool Windows
    theory_id: 15920
  - title: Layout Editor
    theory_id: 14815
  - title: Running your app
    theory_id: 11320
  - title: "Linear, Frame, Relative layouts"
    theory_id: 11981
  - title: LinearLayout in Action
    theory_id: 17619
  - title: "Text, images, and buttons"
    theory_id: 12918
  1:
  - title: Binary numbers
    theory_id: 5544
  - title: Hexadecimal numbers
    theory_id: 8788
  - title: Feedback
    theory_id: 15308
  - title: If expression
    theory_id: 4625
  - title: Repeating blocks
    theory_id: 4643
  - title: Equality
    theory_id: 11236
  - title: Unicode
    theory_id: 7899
  - title: Characters
    theory_id: 4680
  - title: Ranges
    theory_id: 4633
  - title: When expression
    theory_id: 4631
  - title: Functional decomposition
    theory_id: 12668
  - title: Default arguments
    theory_id: 4637
  - title: Named arguments
    theory_id: 4640
  - title: Constructors
    theory_id: 10740
  - title: Member functions
    theory_id: 6364
  - title: Introduction to MutableList
    theory_id: 14879
  - title: For loop and ranges
    theory_id: 4652
  - title: Work with MutableLists
    theory_id: 14902
  - title: For loop and lists
    theory_id: 15022
  - title: Introduction to collections
    theory_id: 10390
  - title: List
    theory_id: 10730
  - title: Mutable List
    theory_id: 11032
  - title: Working with strings
    theory_id: 12561
  - title: Functions as objects
    theory_id: 5991
  - title: Lambda expressions
    theory_id: 6154
  - title: Encapsulation
    theory_id: 8519
  - title: Property accessors
    theory_id: 10511
  - title: Introduction to generic programming
    theory_id: 14698
  - title: Generic functions
    theory_id: 16052
  - title: Retrieving Declared Views
    theory_id: 20346
  - title: Toast
    theory_id: 11973
  - title: Event listeners
    theory_id: 12822
